- name: PLAY-1
  hosts: localhost
  tasks:
    - name: PLAY-1 and TASK-1
      ansible.built.debug:
        msg: "Hello from play1 and task1"

- name: PLAY-2
  hosts: localhost
  tasks:
    - name: PLAY-2 and TASK-2
      ansible.built.debug:
        msg:"Hello from play2 and task2"





