- name: ansible variables
  hosts: localhost
  vars:
    empId: "12343"  
    empname: "Nanda"
    company: "google"
  tasks:
   - name: printing variables
     ansible.builtin.debug:
        msg:"Hi your {{empId}} is and your name is {{empname}} and the companyname is{{company}}"
    


