- name: ansible variables
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
   - name: printing variables
     ansible.builtin.debug:
        msg: "Hi your {{empId}} is and your name is {{empname}} and the companyname is {{company}}"
    


- name: overriding variables
  hosts: localhost
  vars:
    empId: "12343"  
    empname: "Nanda"
    company: "google"
  tasks:
    - name: local variables
      vars:
        company: "microsoft"
      ansible.builtin.debug:
        msg: "Hi your {{empId}} is and your name is {{empname}} and the companyname is {{company}}"

- name: variables from prompting
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: "please enter your username"
      private: false
    - name: PASSWORD
      prompt: "please enter password"
      private: true
  tasks:
   - name: "printing data from prompts"
     ansible.builtin.debug:
        msg: "Hi Yourname is {{USERNAME}} and your password is {{PASSWORD}}"

        